// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SawaryAPI.Data;

#nullable disable

namespace SawaryAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Arabic_100_CI_AS")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SawaryAPI.Models.AboutContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FaqTitleAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaqTitleEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroScrollHintAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroScrollHintEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroStatementAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroStatementEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroTitleAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroTitleEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationAddressAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationAddressEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationGalleryAltAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationGalleryAltEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationMapComingSoonAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationMapComingSoonEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationMapTitleAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationMapTitleEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationTitleAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationTitleEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectionLabelFaqAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectionLabelFaqEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectionLabelStatsAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectionLabelStatsEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectionLabelTeamStructureAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectionLabelTeamStructureEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectionLabelVisitUsAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectionLabelVisitUsEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectionLabelWhoWeAreAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectionLabelWhoWeAreEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamImageAltAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamImageAltEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeamPhotoHeight")
                        .HasColumnType("int");

                    b.Property<string>("TeamPhotoPublicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamPhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeamPhotoWidth")
                        .HasColumnType("int");

                    b.Property<string>("TeamTitleAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamTitleEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisionBodyAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisionBodyEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisionTitleAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisionTitleEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AboutContent");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FaqTitleAr = "الأسئلة الشائعة",
                            FaqTitleEn = "Frequently Asked Questions",
                            HeroScrollHintAr = "مرر",
                            HeroScrollHintEn = "Scroll",
                            HeroStatementAr = "نَنحَت الفراغات بفنّيّة عالية، لِنُقَـدِّم تجارب بصرية تَجمَع بين أصالة الثقافة العربية ورُوح التصميم المُعاصِر، من السعودية نَنطَلِق بروح تنافسية لتحقيق العالمية، في كُلّ تفصيل نَصنَعه هو احتفاء بالهُوِيّة، وكُلّ مشروع نُنَفِّذُه هو قصة تُروَى بَدأَتْها سَوَارِي.",
                            HeroStatementEn = "We carve spaces with great artistry to deliver visual experiences that blend the authenticity of Arab culture with the spirit of contemporary design. From Saudi Arabia, we set out with a competitive spirit to reach the world. Every detail we craft is a celebration of identity, and every project we execute is a story whose telling Sawary began.",
                            HeroTitleAr = "في ســـواري",
                            HeroTitleEn = "At Sawary",
                            LocationAddressAr = "8694 شارع خالد بن الوليد - حي الروضة - الرياض",
                            LocationAddressEn = "8694 Khalid bin Al-Walid St - Al Rawdah Dist. - Riyadh",
                            LocationGalleryAltAr = "مقر سواري",
                            LocationGalleryAltEn = "Sawary headquarters",
                            LocationMapComingSoonAr = "الخريطة قريباً",
                            LocationMapComingSoonEn = "Map coming soon",
                            LocationMapTitleAr = "موقع سواري على الخريطة",
                            LocationMapTitleEn = "Sawary location on the map",
                            LocationTitleAr = "موقعنا",
                            LocationTitleEn = "Our Location",
                            SectionLabelFaqAr = "استفساراتكم",
                            SectionLabelFaqEn = "Inquiries",
                            SectionLabelStatsAr = "بالأرقام",
                            SectionLabelStatsEn = "By The Numbers",
                            SectionLabelTeamStructureAr = "هيكل المنظومة",
                            SectionLabelTeamStructureEn = "Team Structure",
                            SectionLabelVisitUsAr = "زورونا",
                            SectionLabelVisitUsEn = "Visit Us",
                            SectionLabelWhoWeAreAr = "من نحن",
                            SectionLabelWhoWeAreEn = "Who We Are",
                            TeamImageAltAr = "هيكلية فريق سواري",
                            TeamImageAltEn = "Sawary team structure",
                            TeamPhotoHeight = 1575,
                            TeamPhotoPublicId = "",
                            TeamPhotoUrl = "/images/about/employeStrucure.webp",
                            TeamPhotoWidth = 2800,
                            TeamTitleAr = "الفريـــق",
                            TeamTitleEn = "The Team",
                            VisionBodyAr = "كما بَدأنا بتغيير المفاهيم في التَّصميم الدَّاخلي خاصَّة، نسعى لتحسين وإحداث ثورة في عالم التَّصميم والبناء عامَّة، لنحقِّق تجربة فريدة ترتقي بذائقة عملائنا من النُّخبة المختارة بعناية.",
                            VisionBodyEn = "Just as we began by changing the concepts of interior design specifically, we strive to improve and revolutionize the world of design and construction in general — delivering a unique experience that elevates the taste of our carefully chosen, elite clients.",
                            VisionTitleAr = "رؤيتنا",
                            VisionTitleEn = "Our Vision"
                        });
                });

            modelBuilder.Entity("SawaryAPI.Models.AboutFaqItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AboutContentId")
                        .HasColumnType("int");

                    b.Property<string>("ActionHref")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActionLabelAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActionLabelEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnswerAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnswerEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("QuestionAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AboutContentId");

                    b.ToTable("AboutFaqItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AboutContentId = 1,
                            AnswerAr = "نقدم التصميم الداخلي والخارجي ثلاثي الأبعاد وأيضاً التشطيبات والأثاث بشكل كامل.",
                            AnswerEn = "We provide 3D interior and exterior design, as well as complete finishing and furniture.",
                            OrderIndex = 0,
                            QuestionAr = "الخدمات؟",
                            QuestionEn = "Services?"
                        },
                        new
                        {
                            Id = 2,
                            AboutContentId = 1,
                            ActionHref = "/services",
                            ActionLabelAr = "رحلة العميل",
                            ActionLabelEn = "Client Journey",
                            AnswerAr = "نستقبل جميع العملاء ونصمم وننفذ المشاريع السكنية والتجارية وغيرها.",
                            AnswerEn = "We welcome all clients and design and execute residential, commercial, and other projects.",
                            OrderIndex = 1,
                            QuestionAr = "العملاء؟",
                            QuestionEn = "Clients?"
                        },
                        new
                        {
                            Id = 3,
                            AboutContentId = 1,
                            AnswerAr = "كل مشروع له خطة عمل مدروسة ونحدد المدة الزمنية حسب المتطلبات والمواعيد، ولكن عادةً ما تكون المدة المعتادة لمشاريع التصميم 45 يوم عمل.",
                            AnswerEn = "Every project has a carefully studied work plan, and we set the timeline based on requirements and deadlines — though design projects typically take around 45 working days.",
                            OrderIndex = 2,
                            QuestionAr = "المدة؟",
                            QuestionEn = "Duration?"
                        },
                        new
                        {
                            Id = 4,
                            AboutContentId = 1,
                            AnswerAr = "نتميز بقدرة على توفير كل من المواد الطبيعية والصناعية ونستخدمها بشكل مناسب لكل مشروع وبجودة عالية تليق بسواري.",
                            AnswerEn = "We are able to provide both natural and synthetic materials, using them appropriately for each project with the high quality befitting Sawary.",
                            OrderIndex = 3,
                            QuestionAr = "نوع المواد؟",
                            QuestionEn = "Materials?"
                        },
                        new
                        {
                            Id = 5,
                            AboutContentId = 1,
                            ActionHref = "/contact",
                            ActionLabelAr = "احجز استشارتك المجانية",
                            ActionLabelEn = "Book Your Free Consultation",
                            AnswerAr = "التواصل عبر الهاتف لخدمة العملاء أو عن طريق البريد الإلكتروني.",
                            AnswerEn = "Reach us by phone for customer service or by email.",
                            OrderIndex = 4,
                            QuestionAr = "التواصل؟",
                            QuestionEn = "Contact?"
                        });
                });

            modelBuilder.Entity("SawaryAPI.Models.AboutStatItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AboutContentId")
                        .HasColumnType("int");

                    b.Property<string>("LabelAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LabelEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("Suffix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AboutContentId");

                    b.ToTable("AboutStatItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AboutContentId = 1,
                            LabelAr = "عاماً من الخبرة",
                            LabelEn = "Years of Experience",
                            OrderIndex = 0,
                            Suffix = "+",
                            Value = 12
                        },
                        new
                        {
                            Id = 2,
                            AboutContentId = 1,
                            LabelAr = "مشروع منجز",
                            LabelEn = "Completed Projects",
                            OrderIndex = 1,
                            Suffix = "+",
                            Value = 500
                        },
                        new
                        {
                            Id = 3,
                            AboutContentId = 1,
                            LabelAr = "عميل راضٍ",
                            LabelEn = "Satisfied Clients",
                            OrderIndex = 2,
                            Suffix = "+",
                            Value = 7000
                        });
                });

            modelBuilder.Entity("SawaryAPI.Models.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AdminUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "$2a$11$33cMVDQjr.eIkBdXauEcp.O56VnEj/i27T.Yf0njbu/hJ4tX9VK32",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("SawaryAPI.Models.ContactPhoneNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContactSettingsId")
                        .HasColumnType("int");

                    b.Property<string>("LabelAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LabelEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContactSettingsId");

                    b.ToTable("ContactPhoneNumbers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactSettingsId = 1,
                            Number = "+966500175000",
                            OrderIndex = 0
                        });
                });

            modelBuilder.Entity("SawaryAPI.Models.ContactSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhatsAppNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContactSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "sawarydecor@gmail.com",
                            WhatsAppNumber = "966500175000"
                        });
                });

            modelBuilder.Entity("SawaryAPI.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CoverImageHeight")
                        .HasColumnType("int");

                    b.Property<string>("CoverImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CoverImageWidth")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("SawaryAPI.Models.ProjectImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SectionId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SectionId");

                    b.ToTable("ProjectImages");
                });

            modelBuilder.Entity("SawaryAPI.Models.ProjectSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectSections");
                });

            modelBuilder.Entity("SawaryAPI.Models.ProjectTag", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("ProjectId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ProjectTag");
                });

            modelBuilder.Entity("SawaryAPI.Models.ServiceCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("PublicId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("ServiceCards");
                });

            modelBuilder.Entity("SawaryAPI.Models.ServiceSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroImagePublicId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("ServiceSections");
                });

            modelBuilder.Entity("SawaryAPI.Models.SocialLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContactSettingsId")
                        .HasColumnType("int");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContactSettingsId");

                    b.ToTable("SocialLinks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactSettingsId = 1,
                            OrderIndex = 0,
                            Platform = "instagram",
                            Url = "https://www.instagram.com/sawary.de/"
                        },
                        new
                        {
                            Id = 2,
                            ContactSettingsId = 1,
                            OrderIndex = 1,
                            Platform = "x",
                            Url = "https://x.com/SawaryDe"
                        },
                        new
                        {
                            Id = 3,
                            ContactSettingsId = 1,
                            OrderIndex = 2,
                            Platform = "youtube",
                            Url = "https://www.youtube.com/@SAWARYDE"
                        },
                        new
                        {
                            Id = 4,
                            ContactSettingsId = 1,
                            OrderIndex = 3,
                            Platform = "pinterest",
                            Url = "https://www.pinterest.com/sawarydecorproject/"
                        },
                        new
                        {
                            Id = 5,
                            ContactSettingsId = 1,
                            OrderIndex = 4,
                            Platform = "tiktok",
                            Url = "https://www.tiktok.com/@sawary.de"
                        });
                });

            modelBuilder.Entity("SawaryAPI.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NameAr = "تنفيذ تجاري",
                            NameEn = "Commercial Execution",
                            OrderIndex = 0,
                            Slug = "commercial"
                        },
                        new
                        {
                            Id = 2,
                            NameAr = "تنفيذ سكني",
                            NameEn = "Residential Execution",
                            OrderIndex = 1,
                            Slug = "residential"
                        },
                        new
                        {
                            Id = 3,
                            NameAr = "تصميم",
                            NameEn = "Design",
                            OrderIndex = 2,
                            Slug = "design"
                        });
                });

            modelBuilder.Entity("SawaryAPI.Models.AboutFaqItem", b =>
                {
                    b.HasOne("SawaryAPI.Models.AboutContent", "AboutContent")
                        .WithMany("FaqItems")
                        .HasForeignKey("AboutContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AboutContent");
                });

            modelBuilder.Entity("SawaryAPI.Models.AboutStatItem", b =>
                {
                    b.HasOne("SawaryAPI.Models.AboutContent", "AboutContent")
                        .WithMany("StatItems")
                        .HasForeignKey("AboutContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AboutContent");
                });

            modelBuilder.Entity("SawaryAPI.Models.ContactPhoneNumber", b =>
                {
                    b.HasOne("SawaryAPI.Models.ContactSettings", "ContactSettings")
                        .WithMany("PhoneNumbers")
                        .HasForeignKey("ContactSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactSettings");
                });

            modelBuilder.Entity("SawaryAPI.Models.ProjectImage", b =>
                {
                    b.HasOne("SawaryAPI.Models.Project", "Project")
                        .WithMany("Images")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SawaryAPI.Models.ProjectSection", "Section")
                        .WithMany("Images")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Project");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("SawaryAPI.Models.ProjectSection", b =>
                {
                    b.HasOne("SawaryAPI.Models.Project", "Project")
                        .WithMany("Sections")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SawaryAPI.Models.ProjectTag", b =>
                {
                    b.HasOne("SawaryAPI.Models.Project", "Project")
                        .WithMany("ProjectTags")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SawaryAPI.Models.Tag", "Tag")
                        .WithMany("ProjectTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("SawaryAPI.Models.ServiceCard", b =>
                {
                    b.HasOne("SawaryAPI.Models.ServiceSection", "Section")
                        .WithMany("Cards")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("SawaryAPI.Models.SocialLink", b =>
                {
                    b.HasOne("SawaryAPI.Models.ContactSettings", "ContactSettings")
                        .WithMany("SocialLinks")
                        .HasForeignKey("ContactSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactSettings");
                });

            modelBuilder.Entity("SawaryAPI.Models.AboutContent", b =>
                {
                    b.Navigation("FaqItems");

                    b.Navigation("StatItems");
                });

            modelBuilder.Entity("SawaryAPI.Models.ContactSettings", b =>
                {
                    b.Navigation("PhoneNumbers");

                    b.Navigation("SocialLinks");
                });

            modelBuilder.Entity("SawaryAPI.Models.Project", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("ProjectTags");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("SawaryAPI.Models.ProjectSection", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("SawaryAPI.Models.ServiceSection", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("SawaryAPI.Models.Tag", b =>
                {
                    b.Navigation("ProjectTags");
                });
#pragma warning restore 612, 618
        }
    }
}
